spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

app:
  cache:
    ttl-seconds: 300

server:
  port: 8081