spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    name: orders


server:
  port: 8082